### ISSUE TITLE
obexftp and obexfs?

### ISSUE THREAD

**Issue by cicku** [zuckschwerdt/obexftp#1]
Hi,

I'm the maintainer of obexftp RPM package in Fedora, here are some questions:
1. Since obexfs is merged into obexftp, and obexfs has been as a
   separate package in Fedora a long time, is it proper to let obexftp
   obsolete obexfs and provides obexfs?I think of this because obexftp
   now provides same binary of obexfs:

/usr/bin/obexautofs
/usr/bin/obexfs

But, is obexfs still existing? If so I think such obsoletes and
provides are fine, otherwise:
1. The second choice to me is that creating a subpackage obexftp-fuse,
   and put these 2 binaries into this package.

I'm hesitanted now...

Thanks.

**Comment by krichter722** [comment]
Why has this been closed without any reaction?

**Comment by zuckschwerdt** [comment]
ObexFTP is not maintained or developed here.

**Comment by krichter722** [comment]
Do you know where it is maintained?

**Comment by Mathnerd314** [comment]
See http://sourceforge.net/p/openobex/mailman/openobex-users/thread/201203191817.28804.post%40hendrik-sattler.de/; Hendrik Sattler is the (unofficial) maintainer. His last release was in 2013.

There were Gitorious repos, which have since migrated to GitLab: https://gitlab.com/u/hsattler. That seems to be the place to file any new issues/patches.

Meanwhile, there is also obexd, which provides a D-Bus API. There are many clients (including GUIs for KDE, Gnome, etc.); for the command-line it seems https://github.com/khvzak/bluez-tools is being maintained. But this does not provide the FUSE filesystem or other features of obexftp; it would be nice if someone ported them (Hendrik mentioned he might do it but I can find no sign of such activity). The projects are both GPLv2 so there is no license issue with sharing code.
